# Generated by Django 6.0.7 on 2026-07-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0002_alter_seat_options_rename_type_hall_hall_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster_url', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('duration', models.PositiveIntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Скоро в кіно'), ('ACTIVE', 'В прокаті'), ('ARCHIVED', 'Архів')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('slot', models.CharField(choices=[('10:00', '10:00'), ('14:00', '14:00'), ('18:00', '18:00'), ('22:00', '22:00')], default='10:00', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cinemas.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='movies.movie')),
            ],
            options={
                'ordering': ['date', 'slot'],
                'unique_together': {('hall', 'date', 'slot')},
            },
        ),
    ]
