# Generated by Django 6.0.7 on 2026-07-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Скоро в кіно'), ('active', 'В прокаті'), ('archived', 'Архів')], default='active', max_length=20),
        ),
    ]
