# Generated by Django 6.0.7 on 2026-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='date',
            field=models.DateField(),
        ),
    ]
