# Generated by Django 6.0.7 on 2026-07-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ('row_number', 'seat_number')},
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='type',
            new_name='hall_type',
        ),
    ]
